image: "public.ecr.aws/apstra-juniper/goapstra-ci:latest"
pipelines:
  pull-requests:
    '**':
      - parallel:
          - step:
              # Uncomment when self-hosted environment is ready
              # runs-on:
              #   - self.hosted
              #   - linux
              name: staticcheck lint
              script:
                - make lint-staticcheck
          - step:
              # Uncomment when self-hosted environment is ready
              # runs-on:
              #   - self.hosted
              #   - linux
              name: revive linter
              script:
                - make lint-revive
          - step:
              # Uncomment when self-hosted environment is ready
              # runs-on:
              #   - self.hosted
              #   - linux
              name: go format check
              script:
                - make fmt-check
          - step:
              # Uncomment when self-hosted environment is ready
              # runs-on:
              #   - self.hosted
              #   - linux
              name: unit tests
              script:
                - make unit-tests
          - step:
              # Uncomment when self-hosted environment is ready
              # runs-on:
              #   - self.hosted
              #   - linux
              name: go vet
              script:
                - make vet
