// Copyright (c) Juniper Networks, Inc., 2024-2025.
// All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// contents of this file are auto-generated by ./generator/generator.go - DO NOT EDIT

package enum

import (
	"encoding/json"

	oenum "github.com/orsinium-labs/enum"
)

var (
	_ enum             = (*ApiFeature)(nil)
	_ json.Marshaler   = (*ApiFeature)(nil)
	_ json.Unmarshaler = (*ApiFeature)(nil)
)

func (o ApiFeature) String() string {
	return o.Value
}

func (o *ApiFeature) FromString(s string) error {
	if ApiFeatures.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o ApiFeature) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *ApiFeature) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*ConfigletSection)(nil)
	_ json.Marshaler   = (*ConfigletSection)(nil)
	_ json.Unmarshaler = (*ConfigletSection)(nil)
)

func (o ConfigletSection) String() string {
	return o.Value
}

func (o *ConfigletSection) FromString(s string) error {
	if ConfigletSections.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o ConfigletSection) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *ConfigletSection) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*ConfigletStyle)(nil)
	_ json.Marshaler   = (*ConfigletStyle)(nil)
	_ json.Unmarshaler = (*ConfigletStyle)(nil)
)

func (o ConfigletStyle) String() string {
	return o.Value
}

func (o *ConfigletStyle) FromString(s string) error {
	if ConfigletStyles.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o ConfigletStyle) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *ConfigletStyle) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*DeployMode)(nil)
	_ json.Marshaler   = (*DeployMode)(nil)
	_ json.Unmarshaler = (*DeployMode)(nil)
)

func (o DeployMode) String() string {
	return o.Value
}

func (o *DeployMode) FromString(s string) error {
	if DeployModes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o DeployMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *DeployMode) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*DeviceProfileType)(nil)
	_ json.Marshaler   = (*DeviceProfileType)(nil)
	_ json.Unmarshaler = (*DeviceProfileType)(nil)
)

func (o DeviceProfileType) String() string {
	return o.Value
}

func (o *DeviceProfileType) FromString(s string) error {
	if DeviceProfileTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o DeviceProfileType) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *DeviceProfileType) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*DhcpServiceMode)(nil)
	_ json.Marshaler   = (*DhcpServiceMode)(nil)
	_ json.Unmarshaler = (*DhcpServiceMode)(nil)
)

func (o DhcpServiceMode) String() string {
	return o.Value
}

func (o *DhcpServiceMode) FromString(s string) error {
	if DhcpServiceModes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o DhcpServiceMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *DhcpServiceMode) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*EndpointPolicyStatus)(nil)
	_ json.Marshaler   = (*EndpointPolicyStatus)(nil)
	_ json.Unmarshaler = (*EndpointPolicyStatus)(nil)
)

func (o EndpointPolicyStatus) String() string {
	return o.Value
}

func (o *EndpointPolicyStatus) FromString(s string) error {
	if EndpointPolicyStatuses.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o EndpointPolicyStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *EndpointPolicyStatus) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*FFResourceType)(nil)
	_ json.Marshaler   = (*FFResourceType)(nil)
	_ json.Unmarshaler = (*FFResourceType)(nil)
)

func (o FFResourceType) String() string {
	return o.Value
}

func (o *FFResourceType) FromString(s string) error {
	if FFResourceTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o FFResourceType) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *FFResourceType) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*FabricConnectivityDesign)(nil)
	_ json.Marshaler   = (*FabricConnectivityDesign)(nil)
	_ json.Unmarshaler = (*FabricConnectivityDesign)(nil)
)

func (o FabricConnectivityDesign) String() string {
	return o.Value
}

func (o *FabricConnectivityDesign) FromString(s string) error {
	if FabricConnectivityDesigns.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o FabricConnectivityDesign) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *FabricConnectivityDesign) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*FeatureSwitch)(nil)
	_ json.Marshaler   = (*FeatureSwitch)(nil)
	_ json.Unmarshaler = (*FeatureSwitch)(nil)
)

func (o FeatureSwitch) String() string {
	return o.Value
}

func (o *FeatureSwitch) FromString(s string) error {
	if FeatureSwitches.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o FeatureSwitch) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *FeatureSwitch) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*IbaWidgetAggregationType)(nil)
	_ json.Marshaler   = (*IbaWidgetAggregationType)(nil)
	_ json.Unmarshaler = (*IbaWidgetAggregationType)(nil)
)

func (o IbaWidgetAggregationType) String() string {
	return o.Value
}

func (o *IbaWidgetAggregationType) FromString(s string) error {
	if IbaWidgetAggregationTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o IbaWidgetAggregationType) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *IbaWidgetAggregationType) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*IbaWidgetCombineGraph)(nil)
	_ json.Marshaler   = (*IbaWidgetCombineGraph)(nil)
	_ json.Unmarshaler = (*IbaWidgetCombineGraph)(nil)
)

func (o IbaWidgetCombineGraph) String() string {
	return o.Value
}

func (o *IbaWidgetCombineGraph) FromString(s string) error {
	if IbaWidgetCombineGraphs.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o IbaWidgetCombineGraph) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *IbaWidgetCombineGraph) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*IbaWidgetDataSource)(nil)
	_ json.Marshaler   = (*IbaWidgetDataSource)(nil)
	_ json.Unmarshaler = (*IbaWidgetDataSource)(nil)
)

func (o IbaWidgetDataSource) String() string {
	return o.Value
}

func (o *IbaWidgetDataSource) FromString(s string) error {
	if IbaWidgetDataSources.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o IbaWidgetDataSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *IbaWidgetDataSource) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*IbaWidgetType)(nil)
	_ json.Marshaler   = (*IbaWidgetType)(nil)
	_ json.Unmarshaler = (*IbaWidgetType)(nil)
)

func (o IbaWidgetType) String() string {
	return o.Value
}

func (o *IbaWidgetType) FromString(s string) error {
	if IbaWidgetTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o IbaWidgetType) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *IbaWidgetType) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*InterfaceNumberingIpv4Type)(nil)
	_ json.Marshaler   = (*InterfaceNumberingIpv4Type)(nil)
	_ json.Unmarshaler = (*InterfaceNumberingIpv4Type)(nil)
)

func (o InterfaceNumberingIpv4Type) String() string {
	return o.Value
}

func (o *InterfaceNumberingIpv4Type) FromString(s string) error {
	if InterfaceNumberingIpv4Types.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o InterfaceNumberingIpv4Type) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *InterfaceNumberingIpv4Type) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*InterfaceNumberingIpv6Type)(nil)
	_ json.Marshaler   = (*InterfaceNumberingIpv6Type)(nil)
	_ json.Unmarshaler = (*InterfaceNumberingIpv6Type)(nil)
)

func (o InterfaceNumberingIpv6Type) String() string {
	return o.Value
}

func (o *InterfaceNumberingIpv6Type) FromString(s string) error {
	if InterfaceNumberingIpv6Types.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o InterfaceNumberingIpv6Type) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *InterfaceNumberingIpv6Type) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*JunosEvpnIrbMode)(nil)
	_ json.Marshaler   = (*JunosEvpnIrbMode)(nil)
	_ json.Unmarshaler = (*JunosEvpnIrbMode)(nil)
)

func (o JunosEvpnIrbMode) String() string {
	return o.Value
}

func (o *JunosEvpnIrbMode) FromString(s string) error {
	if JunosEvpnIrbModes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o JunosEvpnIrbMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *JunosEvpnIrbMode) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*LinkSpeed)(nil)
	_ json.Marshaler   = (*LinkSpeed)(nil)
	_ json.Unmarshaler = (*LinkSpeed)(nil)
)

func (o LinkSpeed) String() string {
	return o.Value
}

func (o *LinkSpeed) FromString(s string) error {
	if LinkSpeeds.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o LinkSpeed) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *LinkSpeed) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*LockStatus)(nil)
	_ json.Marshaler   = (*LockStatus)(nil)
	_ json.Unmarshaler = (*LockStatus)(nil)
)

func (o LockStatus) String() string {
	return o.Value
}

func (o *LockStatus) FromString(s string) error {
	if LockStatuses.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o LockStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *LockStatus) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*LockType)(nil)
	_ json.Marshaler   = (*LockType)(nil)
	_ json.Unmarshaler = (*LockType)(nil)
)

func (o LockType) String() string {
	return o.Value
}

func (o *LockType) FromString(s string) error {
	if LockTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o LockType) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *LockType) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*NodeRole)(nil)
	_ json.Marshaler   = (*NodeRole)(nil)
	_ json.Unmarshaler = (*NodeRole)(nil)
)

func (o NodeRole) String() string {
	return o.Value
}

func (o *NodeRole) FromString(s string) error {
	if NodeRoles.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o NodeRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *NodeRole) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*PolicyApplicationPointType)(nil)
	_ json.Marshaler   = (*PolicyApplicationPointType)(nil)
	_ json.Unmarshaler = (*PolicyApplicationPointType)(nil)
)

func (o PolicyApplicationPointType) String() string {
	return o.Value
}

func (o *PolicyApplicationPointType) FromString(s string) error {
	if PolicyApplicationPointTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o PolicyApplicationPointType) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *PolicyApplicationPointType) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*PolicyRuleAction)(nil)
	_ json.Marshaler   = (*PolicyRuleAction)(nil)
	_ json.Unmarshaler = (*PolicyRuleAction)(nil)
)

func (o PolicyRuleAction) String() string {
	return o.Value
}

func (o *PolicyRuleAction) FromString(s string) error {
	if PolicyRuleActions.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o PolicyRuleAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *PolicyRuleAction) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*PolicyRuleProtocol)(nil)
	_ json.Marshaler   = (*PolicyRuleProtocol)(nil)
	_ json.Unmarshaler = (*PolicyRuleProtocol)(nil)
)

func (o PolicyRuleProtocol) String() string {
	return o.Value
}

func (o *PolicyRuleProtocol) FromString(s string) error {
	if PolicyRuleProtocols.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o PolicyRuleProtocol) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *PolicyRuleProtocol) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*PortRole)(nil)
	_ json.Marshaler   = (*PortRole)(nil)
	_ json.Unmarshaler = (*PortRole)(nil)
)

func (o PortRole) String() string {
	return o.Value
}

func (o *PortRole) FromString(s string) error {
	if PortRoles.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o PortRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *PortRole) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*RedundancyGroupType)(nil)
	_ json.Marshaler   = (*RedundancyGroupType)(nil)
	_ json.Unmarshaler = (*RedundancyGroupType)(nil)
)

func (o RedundancyGroupType) String() string {
	return o.Value
}

func (o *RedundancyGroupType) FromString(s string) error {
	if RedundancyGroupTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o RedundancyGroupType) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *RedundancyGroupType) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*RefDesign)(nil)
	_ json.Marshaler   = (*RefDesign)(nil)
	_ json.Unmarshaler = (*RefDesign)(nil)
)

func (o RefDesign) String() string {
	return o.Value
}

func (o *RefDesign) FromString(s string) error {
	if RefDesigns.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o RefDesign) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *RefDesign) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*RemoteGatewayRouteType)(nil)
	_ json.Marshaler   = (*RemoteGatewayRouteType)(nil)
	_ json.Unmarshaler = (*RemoteGatewayRouteType)(nil)
)

func (o RemoteGatewayRouteType) String() string {
	return o.Value
}

func (o *RemoteGatewayRouteType) FromString(s string) error {
	if RemoteGatewayRouteTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o RemoteGatewayRouteType) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *RemoteGatewayRouteType) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*RenderedConfigType)(nil)
	_ json.Marshaler   = (*RenderedConfigType)(nil)
	_ json.Unmarshaler = (*RenderedConfigType)(nil)
)

func (o RenderedConfigType) String() string {
	return o.Value
}

func (o *RenderedConfigType) FromString(s string) error {
	if RenderedConfigTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o RenderedConfigType) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *RenderedConfigType) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*ResourcePoolType)(nil)
	_ json.Marshaler   = (*ResourcePoolType)(nil)
	_ json.Unmarshaler = (*ResourcePoolType)(nil)
)

func (o ResourcePoolType) String() string {
	return o.Value
}

func (o *ResourcePoolType) FromString(s string) error {
	if ResourcePoolTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o ResourcePoolType) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *ResourcePoolType) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*RoutingZoneConstraintMode)(nil)
	_ json.Marshaler   = (*RoutingZoneConstraintMode)(nil)
	_ json.Unmarshaler = (*RoutingZoneConstraintMode)(nil)
)

func (o RoutingZoneConstraintMode) String() string {
	return o.Value
}

func (o *RoutingZoneConstraintMode) FromString(s string) error {
	if RoutingZoneConstraintModes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o RoutingZoneConstraintMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *RoutingZoneConstraintMode) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*SecurityZoneType)(nil)
	_ json.Marshaler   = (*SecurityZoneType)(nil)
	_ json.Unmarshaler = (*SecurityZoneType)(nil)
)

func (o SecurityZoneType) String() string {
	return o.Value
}

func (o *SecurityZoneType) FromString(s string) error {
	if SecurityZoneTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o SecurityZoneType) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *SecurityZoneType) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*SpeedUnit)(nil)
	_ json.Marshaler   = (*SpeedUnit)(nil)
	_ json.Unmarshaler = (*SpeedUnit)(nil)
)

func (o SpeedUnit) String() string {
	return o.Value
}

func (o *SpeedUnit) FromString(s string) error {
	if SpeedUnits.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o SpeedUnit) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *SpeedUnit) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*StorageSchemaPath)(nil)
	_ json.Marshaler   = (*StorageSchemaPath)(nil)
	_ json.Unmarshaler = (*StorageSchemaPath)(nil)
)

func (o StorageSchemaPath) String() string {
	return o.Value
}

func (o *StorageSchemaPath) FromString(s string) error {
	if StorageSchemaPaths.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o StorageSchemaPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *StorageSchemaPath) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*SviIpv4Mode)(nil)
	_ json.Marshaler   = (*SviIpv4Mode)(nil)
	_ json.Unmarshaler = (*SviIpv4Mode)(nil)
)

func (o SviIpv4Mode) String() string {
	return o.Value
}

func (o *SviIpv4Mode) FromString(s string) error {
	if SviIpv4Modes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o SviIpv4Mode) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *SviIpv4Mode) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*SviIpv6Mode)(nil)
	_ json.Marshaler   = (*SviIpv6Mode)(nil)
	_ json.Unmarshaler = (*SviIpv6Mode)(nil)
)

func (o SviIpv6Mode) String() string {
	return o.Value
}

func (o *SviIpv6Mode) FromString(s string) error {
	if SviIpv6Modes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o SviIpv6Mode) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *SviIpv6Mode) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*SystemType)(nil)
	_ json.Marshaler   = (*SystemType)(nil)
	_ json.Unmarshaler = (*SystemType)(nil)
)

func (o SystemType) String() string {
	return o.Value
}

func (o *SystemType) FromString(s string) error {
	if SystemTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o SystemType) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *SystemType) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*TcpStateQualifier)(nil)
	_ json.Marshaler   = (*TcpStateQualifier)(nil)
	_ json.Unmarshaler = (*TcpStateQualifier)(nil)
)

func (o TcpStateQualifier) String() string {
	return o.Value
}

func (o *TcpStateQualifier) FromString(s string) error {
	if TcpStateQualifiers.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o TcpStateQualifier) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *TcpStateQualifier) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_ enum             = (*VnType)(nil)
	_ json.Marshaler   = (*VnType)(nil)
	_ json.Unmarshaler = (*VnType)(nil)
)

func (o VnType) String() string {
	return o.Value
}

func (o *VnType) FromString(s string) error {
	if VnTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o VnType) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

func (o *VnType) UnmarshalJSON(bytes []byte) error {
	var s string
	err := json.Unmarshal(bytes, &s)
	if err != nil {
		return err
	}
	return o.FromString(s)
}

var (
	_           enum = new(ApiFeature)
	ApiFeatures      = oenum.New(
		ApiFeatureAiFabric,
		ApiFeatureCentral,
		ApiFeatureEnterprise,
		ApiFeatureFreeform,
		ApiFeatureFullAccess,
		ApiFeatureTaskApi,
	)

	_                 enum = new(ConfigletSection)
	ConfigletSections      = oenum.New(
		ConfigletSectionDeleteBasedInterface,
		ConfigletSectionFile,
		ConfigletSectionFrr,
		ConfigletSectionInterface,
		ConfigletSectionOspf,
		ConfigletSectionSetBasedInterface,
		ConfigletSectionSetBasedSystem,
		ConfigletSectionSystem,
		ConfigletSectionSystemTop,
	)

	_               enum = new(ConfigletStyle)
	ConfigletStyles      = oenum.New(
		ConfigletStyleCumulus,
		ConfigletStyleEos,
		ConfigletStyleJunos,
		ConfigletStyleNxos,
		ConfigletStyleSonic,
	)

	_           enum = new(DeployMode)
	DeployModes      = oenum.New(
		DeployModeDeploy,
		DeployModeDrain,
		DeployModeNone,
		DeployModeReady,
		DeployModeUndeploy,
	)

	_                  enum = new(DeviceProfileType)
	DeviceProfileTypes      = oenum.New(
		DeviceProfileTypeModular,
		DeviceProfileTypeMonolithic,
	)

	_                enum = new(DhcpServiceMode)
	DhcpServiceModes      = oenum.New(
		DhcpServiceModeDisabled,
		DhcpServiceModeEnabled,
	)

	_                      enum = new(EndpointPolicyStatus)
	EndpointPolicyStatuses      = oenum.New(
		EndpointPolicyStatusAssigned,
		EndpointPolicyStatusIncomplete,
		EndpointPolicyStatusReady,
	)

	_               enum = new(FFResourceType)
	FFResourceTypes      = oenum.New(
		FFResourceTypeAsn,
		FFResourceTypeHostIpv4,
		FFResourceTypeHostIpv6,
		FFResourceTypeInt,
		FFResourceTypeIpv4,
		FFResourceTypeIpv6,
		FFResourceTypeVlan,
		FFResourceTypeVni,
	)

	_                         enum = new(FabricConnectivityDesign)
	FabricConnectivityDesigns      = oenum.New(
		FabricConnectivityDesignL3Clos,
		FabricConnectivityDesignL3Collapsed,
		FabricConnectivityDesignRailCollapsed,
	)

	_               enum = new(FeatureSwitch)
	FeatureSwitches      = oenum.New(
		FeatureSwitchEnabled,
		FeatureSwitchDisabled,
	)

	_                         enum = new(IbaWidgetAggregationType)
	IbaWidgetAggregationTypes      = oenum.New(
		IbaWidgetAggregationTypeUnset,
		IbaWidgetAggregationTypeMin,
		IbaWidgetAggregationTypeAverage,
		IbaWidgetAggregationTypeNone,
		IbaWidgetAggregationTypeAnyOf,
		IbaWidgetAggregationTypeLast,
		IbaWidgetAggregationTypeAllOf,
		IbaWidgetAggregationTypeMax,
	)

	_                      enum = new(IbaWidgetCombineGraph)
	IbaWidgetCombineGraphs      = oenum.New(
		IbaWidgetCombineGraphNone,
		IbaWidgetCombineGraphLinear,
		IbaWidgetCombineGraphStacked,
	)

	_                    enum = new(IbaWidgetDataSource)
	IbaWidgetDataSources      = oenum.New(
		IbaWidgetDataSourceRealTime,
		IbaWidgetDataSourceTimeSeries,
	)

	_              enum = new(IbaWidgetType)
	IbaWidgetTypes      = oenum.New(
		IbaWidgetTypeStage,
		IbaWidgetTypeAnomalyHeatmap,
	)

	_                           enum = new(InterfaceNumberingIpv4Type)
	InterfaceNumberingIpv4Types      = oenum.New(
		InterfaceNumberingIpv4TypeNone,
		InterfaceNumberingIpv4TypeNumbered,
	)

	_                           enum = new(InterfaceNumberingIpv6Type)
	InterfaceNumberingIpv6Types      = oenum.New(
		InterfaceNumberingIpv6TypeNone,
		InterfaceNumberingIpv6TypeNumbered,
		InterfaceNumberingIpv6TypeLinkLocal,
	)

	_                 enum = new(JunosEvpnIrbMode)
	JunosEvpnIrbModes      = oenum.New(
		JunosEvpnIrbModeSymmetric,
		JunosEvpnIrbModeAsymmetric,
	)

	_          enum = new(LinkSpeed)
	LinkSpeeds      = oenum.New(
		LinkSpeed10M,
		LinkSpeed10m,
		LinkSpeed100M,
		LinkSpeed100m,
		LinkSpeed1G,
		LinkSpeed1g,
		LinkSpeed2500M,
		LinkSpeed2500m,
		LinkSpeed5G,
		LinkSpeed5g,
		LinkSpeed10G,
		LinkSpeed10g,
		LinkSpeed25G,
		LinkSpeed25g,
		LinkSpeed40G,
		LinkSpeed40g,
		LinkSpeed50G,
		LinkSpeed50g,
		LinkSpeed100G,
		LinkSpeed100g,
		LinkSpeed150G,
		LinkSpeed150g,
		LinkSpeed200G,
		LinkSpeed200g,
		LinkSpeed400G,
		LinkSpeed400g,
		LinkSpeed800G,
		LinkSpeed800g,
	)

	_            enum = new(LockStatus)
	LockStatuses      = oenum.New(
		LockStatusLocked,
		LockStatusLockedByAdmin,
		LockStatusLockedByDeletedUser,
		LockStatusLockedByRestrictedUser,
		LockStatusUnlocked,
	)

	_         enum = new(LockType)
	LockTypes      = oenum.New(
		LockTypeLockedByChanges,
		LockTypeLockedByUser,
		LockTypeUnlocked,
	)

	_         enum = new(NodeRole)
	NodeRoles      = oenum.New(
		NodeRoleAccess,
		NodeRoleGeneric,
		NodeRoleLeaf,
		NodeRoleRemoteGateway,
		NodeRoleSpine,
		NodeRoleSuperspine,
	)

	_                           enum = new(PolicyApplicationPointType)
	PolicyApplicationPointTypes      = oenum.New(
		PolicyApplicationPointTypeGroup,
		PolicyApplicationPointTypeInternal,
		PolicyApplicationPointTypeExternal,
		PolicyApplicationPointTypeSecurityZone,
		PolicyApplicationPointTypeVirtualNetwork,
	)

	_                 enum = new(PolicyRuleAction)
	PolicyRuleActions      = oenum.New(
		PolicyRuleActionDeny,
		PolicyRuleActionDenyLog,
		PolicyRuleActionPermit,
		PolicyRuleActionPermitLog,
	)

	_                   enum = new(PolicyRuleProtocol)
	PolicyRuleProtocols      = oenum.New(
		PolicyRuleProtocolIcmp,
		PolicyRuleProtocolIp,
		PolicyRuleProtocolTcp,
		PolicyRuleProtocolUdp,
	)

	_         enum = new(PortRole)
	PortRoles      = oenum.New(
		PortRoleAccess,
		PortRoleGeneric,
		PortRoleL3Server,
		PortRoleLeaf,
		PortRolePeer,
		PortRoleSpine,
		PortRoleSuperspine,
		PortRoleUnused,
	)

	_                    enum = new(RedundancyGroupType)
	RedundancyGroupTypes      = oenum.New(
		RedundancyGroupTypeEsi,
		RedundancyGroupTypeMlag,
	)

	_          enum = new(RefDesign)
	RefDesigns      = oenum.New(
		RefDesignDatacenter,
		RefDesignFreeform,
		RefDesignRailCollapsed,
	)

	_                       enum = new(RemoteGatewayRouteType)
	RemoteGatewayRouteTypes      = oenum.New(
		RemoteGatewayRouteTypeAll,
		RemoteGatewayRouteTypeFiveOnly,
	)

	_                   enum = new(RenderedConfigType)
	RenderedConfigTypes      = oenum.New(
		RenderedConfigTypeStaging,
		RenderedConfigTypeDeployed,
	)

	_                 enum = new(ResourcePoolType)
	ResourcePoolTypes      = oenum.New(
		ResourcePoolTypeAsn,
		ResourcePoolTypeInt,
		ResourcePoolTypeIpv4,
		ResourcePoolTypeIpv6,
		ResourcePoolTypeVlan,
		ResourcePoolTypeVni,
	)

	_                          enum = new(RoutingZoneConstraintMode)
	RoutingZoneConstraintModes      = oenum.New(
		RoutingZoneConstraintModeNone,
		RoutingZoneConstraintModeAllow,
		RoutingZoneConstraintModeDeny,
	)

	_                 enum = new(SecurityZoneType)
	SecurityZoneTypes      = oenum.New(
		SecurityZoneTypeEvpn,
		SecurityZoneTypeL3Fabric,
		SecurityZoneTypeVirtualL3Fabric,
	)

	_          enum = new(SpeedUnit)
	SpeedUnits      = oenum.New(
		SpeedUnitM,
		SpeedUnitG,
	)

	_                  enum = new(StorageSchemaPath)
	StorageSchemaPaths      = oenum.New(
		StorageSchemaPathARP,
		StorageSchemaPathBGP,
		StorageSchemaPathCppGraph,
		StorageSchemaPathEnvironment,
		StorageSchemaPathGeneric,
		StorageSchemaPathGraph,
		StorageSchemaPathHostname,
		StorageSchemaPathIbaData,
		StorageSchemaPathIbaIntegerData,
		StorageSchemaPathIbaStringData,
		StorageSchemaPathInterface,
		StorageSchemaPathInterfaceCounters,
		StorageSchemaPathLAG,
		StorageSchemaPathLLDP,
		StorageSchemaPathMAC,
		StorageSchemaPathMLAG,
		StorageSchemaPathNSXT,
		StorageSchemaPathOpticalXcvr,
		StorageSchemaPathRoute,
		StorageSchemaPathRouteLookup,
		StorageSchemaPathXcvr,
	)

	_            enum = new(SviIpv4Mode)
	SviIpv4Modes      = oenum.New(
		SviIpv4ModeDisabled,
		SviIpv4ModeEnabled,
		SviIpv4ModeForced,
	)

	_            enum = new(SviIpv6Mode)
	SviIpv6Modes      = oenum.New(
		SviIpv6ModeDisabled,
		SviIpv6ModeEnabled,
		SviIpv6ModeForced,
		SviIpv6ModeLinkLocal,
	)

	_           enum = new(SystemType)
	SystemTypes      = oenum.New(
		SystemTypeServer,
		SystemTypeSwitch,
	)

	_                  enum = new(TcpStateQualifier)
	TcpStateQualifiers      = oenum.New(
		TcpStateQualifierEstablished,
	)

	_       enum = new(VnType)
	VnTypes      = oenum.New(
		VnTypeExternal,
		VnTypeVlan,
		VnTypeVxlan,
	)
)
