// Copyright (c) Juniper Networks, Inc., 2024-2025.
// All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// contents of this file are auto-generated by ./generator/generator.go - DO NOT EDIT

package enum

import (
	"encoding/json"

	oenum "github.com/orsinium-labs/enum"
)

var (
	_ enum             = (*ApiFeature)(nil)
	_ json.Marshaler   = (*ApiFeature)(nil)
	_ json.Unmarshaler = (*ApiFeature)(nil)
)

func (o ApiFeature) String() string {
	return o.Value
}

func (o *ApiFeature) FromString(s string) error {
	if ApiFeatures.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *ApiFeature) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *ApiFeature) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*DeployMode)(nil)
	_ json.Marshaler   = (*DeployMode)(nil)
	_ json.Unmarshaler = (*DeployMode)(nil)
)

func (o DeployMode) String() string {
	return o.Value
}

func (o *DeployMode) FromString(s string) error {
	if DeployModes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *DeployMode) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *DeployMode) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*DeviceProfileType)(nil)
	_ json.Marshaler   = (*DeviceProfileType)(nil)
	_ json.Unmarshaler = (*DeviceProfileType)(nil)
)

func (o DeviceProfileType) String() string {
	return o.Value
}

func (o *DeviceProfileType) FromString(s string) error {
	if DeviceProfileTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *DeviceProfileType) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *DeviceProfileType) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*DhcpServiceMode)(nil)
	_ json.Marshaler   = (*DhcpServiceMode)(nil)
	_ json.Unmarshaler = (*DhcpServiceMode)(nil)
)

func (o DhcpServiceMode) String() string {
	return o.Value
}

func (o *DhcpServiceMode) FromString(s string) error {
	if DhcpServiceModes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *DhcpServiceMode) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *DhcpServiceMode) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*FFResourceType)(nil)
	_ json.Marshaler   = (*FFResourceType)(nil)
	_ json.Unmarshaler = (*FFResourceType)(nil)
)

func (o FFResourceType) String() string {
	return o.Value
}

func (o *FFResourceType) FromString(s string) error {
	if FFResourceTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *FFResourceType) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *FFResourceType) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*FeatureSwitch)(nil)
	_ json.Marshaler   = (*FeatureSwitch)(nil)
	_ json.Unmarshaler = (*FeatureSwitch)(nil)
)

func (o FeatureSwitch) String() string {
	return o.Value
}

func (o *FeatureSwitch) FromString(s string) error {
	if FeatureSwitches.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *FeatureSwitch) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *FeatureSwitch) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*IbaWidgetType)(nil)
	_ json.Marshaler   = (*IbaWidgetType)(nil)
	_ json.Unmarshaler = (*IbaWidgetType)(nil)
)

func (o IbaWidgetType) String() string {
	return o.Value
}

func (o *IbaWidgetType) FromString(s string) error {
	if IbaWidgetTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *IbaWidgetType) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *IbaWidgetType) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*InterfaceNumberingIpv4Type)(nil)
	_ json.Marshaler   = (*InterfaceNumberingIpv4Type)(nil)
	_ json.Unmarshaler = (*InterfaceNumberingIpv4Type)(nil)
)

func (o InterfaceNumberingIpv4Type) String() string {
	return o.Value
}

func (o *InterfaceNumberingIpv4Type) FromString(s string) error {
	if InterfaceNumberingIpv4Types.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *InterfaceNumberingIpv4Type) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *InterfaceNumberingIpv4Type) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*InterfaceNumberingIpv6Type)(nil)
	_ json.Marshaler   = (*InterfaceNumberingIpv6Type)(nil)
	_ json.Unmarshaler = (*InterfaceNumberingIpv6Type)(nil)
)

func (o InterfaceNumberingIpv6Type) String() string {
	return o.Value
}

func (o *InterfaceNumberingIpv6Type) FromString(s string) error {
	if InterfaceNumberingIpv6Types.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *InterfaceNumberingIpv6Type) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *InterfaceNumberingIpv6Type) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*JunosEvpnIrbMode)(nil)
	_ json.Marshaler   = (*JunosEvpnIrbMode)(nil)
	_ json.Unmarshaler = (*JunosEvpnIrbMode)(nil)
)

func (o JunosEvpnIrbMode) String() string {
	return o.Value
}

func (o *JunosEvpnIrbMode) FromString(s string) error {
	if JunosEvpnIrbModes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *JunosEvpnIrbMode) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *JunosEvpnIrbMode) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*PolicyApplicationPointType)(nil)
	_ json.Marshaler   = (*PolicyApplicationPointType)(nil)
	_ json.Unmarshaler = (*PolicyApplicationPointType)(nil)
)

func (o PolicyApplicationPointType) String() string {
	return o.Value
}

func (o *PolicyApplicationPointType) FromString(s string) error {
	if PolicyApplicationPointTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *PolicyApplicationPointType) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *PolicyApplicationPointType) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*PolicyRuleAction)(nil)
	_ json.Marshaler   = (*PolicyRuleAction)(nil)
	_ json.Unmarshaler = (*PolicyRuleAction)(nil)
)

func (o PolicyRuleAction) String() string {
	return o.Value
}

func (o *PolicyRuleAction) FromString(s string) error {
	if PolicyRuleActions.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *PolicyRuleAction) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *PolicyRuleAction) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*PolicyRuleProtocol)(nil)
	_ json.Marshaler   = (*PolicyRuleProtocol)(nil)
	_ json.Unmarshaler = (*PolicyRuleProtocol)(nil)
)

func (o PolicyRuleProtocol) String() string {
	return o.Value
}

func (o *PolicyRuleProtocol) FromString(s string) error {
	if PolicyRuleProtocols.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *PolicyRuleProtocol) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *PolicyRuleProtocol) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*PortRole)(nil)
	_ json.Marshaler   = (*PortRole)(nil)
	_ json.Unmarshaler = (*PortRole)(nil)
)

func (o PortRole) String() string {
	return o.Value
}

func (o *PortRole) FromString(s string) error {
	if PortRoles.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *PortRole) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *PortRole) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*RemoteGatewayRouteType)(nil)
	_ json.Marshaler   = (*RemoteGatewayRouteType)(nil)
	_ json.Unmarshaler = (*RemoteGatewayRouteType)(nil)
)

func (o RemoteGatewayRouteType) String() string {
	return o.Value
}

func (o *RemoteGatewayRouteType) FromString(s string) error {
	if RemoteGatewayRouteTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *RemoteGatewayRouteType) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *RemoteGatewayRouteType) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*RenderedConfigType)(nil)
	_ json.Marshaler   = (*RenderedConfigType)(nil)
	_ json.Unmarshaler = (*RenderedConfigType)(nil)
)

func (o RenderedConfigType) String() string {
	return o.Value
}

func (o *RenderedConfigType) FromString(s string) error {
	if RenderedConfigTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *RenderedConfigType) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *RenderedConfigType) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*ResourcePoolType)(nil)
	_ json.Marshaler   = (*ResourcePoolType)(nil)
	_ json.Unmarshaler = (*ResourcePoolType)(nil)
)

func (o ResourcePoolType) String() string {
	return o.Value
}

func (o *ResourcePoolType) FromString(s string) error {
	if ResourcePoolTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *ResourcePoolType) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *ResourcePoolType) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*RoutingZoneConstraintMode)(nil)
	_ json.Marshaler   = (*RoutingZoneConstraintMode)(nil)
	_ json.Unmarshaler = (*RoutingZoneConstraintMode)(nil)
)

func (o RoutingZoneConstraintMode) String() string {
	return o.Value
}

func (o *RoutingZoneConstraintMode) FromString(s string) error {
	if RoutingZoneConstraintModes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *RoutingZoneConstraintMode) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *RoutingZoneConstraintMode) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*StorageSchemaPath)(nil)
	_ json.Marshaler   = (*StorageSchemaPath)(nil)
	_ json.Unmarshaler = (*StorageSchemaPath)(nil)
)

func (o StorageSchemaPath) String() string {
	return o.Value
}

func (o *StorageSchemaPath) FromString(s string) error {
	if StorageSchemaPaths.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *StorageSchemaPath) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *StorageSchemaPath) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*SviIpv4Mode)(nil)
	_ json.Marshaler   = (*SviIpv4Mode)(nil)
	_ json.Unmarshaler = (*SviIpv4Mode)(nil)
)

func (o SviIpv4Mode) String() string {
	return o.Value
}

func (o *SviIpv4Mode) FromString(s string) error {
	if SviIpv4Modes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *SviIpv4Mode) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *SviIpv4Mode) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*SviIpv6Mode)(nil)
	_ json.Marshaler   = (*SviIpv6Mode)(nil)
	_ json.Unmarshaler = (*SviIpv6Mode)(nil)
)

func (o SviIpv6Mode) String() string {
	return o.Value
}

func (o *SviIpv6Mode) FromString(s string) error {
	if SviIpv6Modes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *SviIpv6Mode) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *SviIpv6Mode) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*TcpStateQualifier)(nil)
	_ json.Marshaler   = (*TcpStateQualifier)(nil)
	_ json.Unmarshaler = (*TcpStateQualifier)(nil)
)

func (o TcpStateQualifier) String() string {
	return o.Value
}

func (o *TcpStateQualifier) FromString(s string) error {
	if TcpStateQualifiers.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *TcpStateQualifier) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *TcpStateQualifier) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_ enum             = (*VnType)(nil)
	_ json.Marshaler   = (*VnType)(nil)
	_ json.Unmarshaler = (*VnType)(nil)
)

func (o VnType) String() string {
	return o.Value
}

func (o *VnType) FromString(s string) error {
	if VnTypes.Parse(s) == nil {
		return newEnumParseError(o, s)
	}
	o.Value = s
	return nil
}

func (o *VnType) MarshalJSON() ([]byte, error) {
	return []byte(o.String()), nil
}

func (o *VnType) UnmarshalJSON(bytes []byte) error {
	return o.FromString(string(bytes))
}

var (
	_           enum = new(ApiFeature)
	ApiFeatures      = oenum.New(
		ApiFeatureAiFabric,
		ApiFeatureCentral,
		ApiFeatureEnterprise,
		ApiFeatureFreeform,
		ApiFeatureFullAccess,
		ApiFeatureTaskApi,
	)

	_           enum = new(DeployMode)
	DeployModes      = oenum.New(
		DeployModeDeploy,
		DeployModeDrain,
		DeployModeNone,
		DeployModeReady,
		DeployModeUndeploy,
	)

	_                  enum = new(DeviceProfileType)
	DeviceProfileTypes      = oenum.New(
		DeviceProfileTypeModular,
		DeviceProfileTypeMonolithic,
	)

	_                enum = new(DhcpServiceMode)
	DhcpServiceModes      = oenum.New(
		DhcpServiceModeDisabled,
		DhcpServiceModeEnabled,
	)

	_               enum = new(FFResourceType)
	FFResourceTypes      = oenum.New(
		FFResourceTypeAsn,
		FFResourceTypeHostIpv4,
		FFResourceTypeHostIpv6,
		FFResourceTypeInt,
		FFResourceTypeIpv4,
		FFResourceTypeIpv6,
		FFResourceTypeVlan,
		FFResourceTypeVni,
	)

	_               enum = new(FeatureSwitch)
	FeatureSwitches      = oenum.New(
		FeatureSwitchEnabled,
		FeatureSwitchDisabled,
	)

	_              enum = new(IbaWidgetType)
	IbaWidgetTypes      = oenum.New(
		IbaWidgetTypeStage,
		IbaWidgetTypeAnomalyHeatmap,
	)

	_                           enum = new(InterfaceNumberingIpv4Type)
	InterfaceNumberingIpv4Types      = oenum.New(
		InterfaceNumberingIpv4TypeNone,
		InterfaceNumberingIpv4TypeNumbered,
	)

	_                           enum = new(InterfaceNumberingIpv6Type)
	InterfaceNumberingIpv6Types      = oenum.New(
		InterfaceNumberingIpv6TypeNone,
		InterfaceNumberingIpv6TypeNumbered,
		InterfaceNumberingIpv6TypeLinkLocal,
	)

	_                 enum = new(JunosEvpnIrbMode)
	JunosEvpnIrbModes      = oenum.New(
		JunosEvpnIrbModeSymmetric,
		JunosEvpnIrbModeAsymmetric,
	)

	_                           enum = new(PolicyApplicationPointType)
	PolicyApplicationPointTypes      = oenum.New(
		PolicyApplicationPointTypeGroup,
		PolicyApplicationPointTypeInternal,
		PolicyApplicationPointTypeExternal,
		PolicyApplicationPointTypeSecurityZone,
		PolicyApplicationPointTypeVirtualNetwork,
	)

	_                 enum = new(PolicyRuleAction)
	PolicyRuleActions      = oenum.New(
		PolicyRuleActionDeny,
		PolicyRuleActionDenyLog,
		PolicyRuleActionPermit,
		PolicyRuleActionPermitLog,
	)

	_                   enum = new(PolicyRuleProtocol)
	PolicyRuleProtocols      = oenum.New(
		PolicyRuleProtocolIcmp,
		PolicyRuleProtocolIp,
		PolicyRuleProtocolTcp,
		PolicyRuleProtocolUdp,
	)

	_         enum = new(PortRole)
	PortRoles      = oenum.New(
		PortRoleAccess,
		PortRoleGeneric,
		PortRoleL3Server,
		PortRoleLeaf,
		PortRolePeer,
		PortRoleSpine,
		PortRoleSuperspine,
		PortRoleUnused,
	)

	_                       enum = new(RemoteGatewayRouteType)
	RemoteGatewayRouteTypes      = oenum.New(
		RemoteGatewayRouteTypeAll,
		RemoteGatewayRouteTypeFiveOnly,
	)

	_                   enum = new(RenderedConfigType)
	RenderedConfigTypes      = oenum.New(
		RenderedConfigTypeStaging,
		RenderedConfigTypeDeployed,
	)

	_                 enum = new(ResourcePoolType)
	ResourcePoolTypes      = oenum.New(
		ResourcePoolTypeAsn,
		ResourcePoolTypeInt,
		ResourcePoolTypeIpv4,
		ResourcePoolTypeIpv6,
		ResourcePoolTypeVlan,
		ResourcePoolTypeVni,
	)

	_                          enum = new(RoutingZoneConstraintMode)
	RoutingZoneConstraintModes      = oenum.New(
		RoutingZoneConstraintModeNone,
		RoutingZoneConstraintModeAllow,
		RoutingZoneConstraintModeDeny,
	)

	_                  enum = new(StorageSchemaPath)
	StorageSchemaPaths      = oenum.New(
		StorageSchemaPathARP,
		StorageSchemaPathBGP,
		StorageSchemaPathCppGraph,
		StorageSchemaPathEnvironment,
		StorageSchemaPathGeneric,
		StorageSchemaPathGraph,
		StorageSchemaPathHostname,
		StorageSchemaPathIbaData,
		StorageSchemaPathIbaIntegerData,
		StorageSchemaPathIbaStringData,
		StorageSchemaPathInterface,
		StorageSchemaPathInterfaceCounters,
		StorageSchemaPathLAG,
		StorageSchemaPathLLDP,
		StorageSchemaPathMAC,
		StorageSchemaPathMLAG,
		StorageSchemaPathNSXT,
		StorageSchemaPathOpticalXcvr,
		StorageSchemaPathRoute,
		StorageSchemaPathRouteLookup,
		StorageSchemaPathXcvr,
	)

	_            enum = new(SviIpv4Mode)
	SviIpv4Modes      = oenum.New(
		SviIpv4ModeDisabled,
		SviIpv4ModeEnabled,
		SviIpv4ModeForced,
	)

	_            enum = new(SviIpv6Mode)
	SviIpv6Modes      = oenum.New(
		SviIpv6ModeDisabled,
		SviIpv6ModeEnabled,
		SviIpv6ModeForced,
		SviIpv6ModeLinkLocal,
	)

	_                  enum = new(TcpStateQualifier)
	TcpStateQualifiers      = oenum.New(
		TcpStateQualifierEstablished,
	)

	_       enum = new(VnType)
	VnTypes      = oenum.New(
		VnTypeExternal,
		VnTypeVlan,
		VnTypeVxlan,
	)
)
