// Copyright (c) Juniper Networks, Inc., 2025-2025.
// All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//go:build integration

package device_test

import (
	"context"
	"testing"
	"time"

	"github.com/Juniper/apstra-go-sdk/apstra"
	"github.com/Juniper/apstra-go-sdk/compatibility"
	"github.com/Juniper/apstra-go-sdk/device"
	"github.com/Juniper/apstra-go-sdk/enum"
	"github.com/Juniper/apstra-go-sdk/internal/pointer"
	"github.com/Juniper/apstra-go-sdk/internal/slice"
	testutils "github.com/Juniper/apstra-go-sdk/internal/test_utils"
	"github.com/Juniper/apstra-go-sdk/internal/test_utils/compare/device"
	testclient "github.com/Juniper/apstra-go-sdk/internal/test_utils/test_client"
	"github.com/hashicorp/go-version"
	"github.com/stretchr/testify/require"
)

func TestProfile_CRUD(t *testing.T) {
	ctx := testutils.ContextWithTestID(t.Context(), t)
	clients := testclient.GetTestClients(t, ctx)

	type testCase struct {
		create device.Profile
		update device.Profile
	}

	testCases := map[string]testCase{
		"vEX_to_EX4400": {
			create: device.Profile{
				Label:                       testutils.RandString(6, "hex"),
				Selector:                    device.Selector{OsVersion: ".*", Model: "VIRTUAL-EX9214", Os: "Junos", Manufacturer: "Juniper"},
				DeviceProfileType:           enum.DeviceProfileTypeMonolithic,
				DualRoutingEngine:           false,
				SoftwareCapabilities:        device.SoftwareCapabilities{Onie: false, ConfigApplySupport: "complete_only", LxcSupport: false},
				ReferenceDesignCapabilities: &device.ReferenceDesignCapabilities{Datacenter: enum.RefDesignCapabilityFullSupport, Freeform: enum.RefDesignCapabilityFullSupport},
				ChassisProfileID:            "",
				HardwareCapabilities: device.HardwareCapabilities{
					FormFactor:      "1RU",
					BFDSupported:    false,
					ECMPLimit:       32,
					RAM:             32,
					BreakoutCapable: nil,
					Userland:        32,
					ASIC:            "Trio",
					RoutingInstance: device.FeatureVersions{device.FeatureVersion{Version: ".*", Enabled: true}},
					VxlanSupported:  false,
					CPU:             "x86",
				},
				SlotCount: pointer.To(0),
				Ports: []device.Port{
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/0", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "10g"}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/0", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}}, Column: 1, ID: 1, Row: 1, FailureDomain: 1, Display: pointer.To(0), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/1", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "10g"}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/1", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}}, Column: 2, ID: 2, Row: 1, FailureDomain: 1, Display: pointer.To(1), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/2", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "10g"}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/2", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}}, Column: 3, ID: 3, Row: 1, FailureDomain: 1, Display: pointer.To(2), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/3", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "10g"}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/3", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}}, Column: 4, ID: 4, Row: 1, FailureDomain: 1, Display: pointer.To(3), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/4", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "10g"}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/4", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}}, Column: 5, ID: 5, Row: 1, FailureDomain: 1, Display: pointer.To(4), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/5", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "10g"}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/5", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}}, Column: 6, ID: 6, Row: 1, FailureDomain: 1, Display: pointer.To(5), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/6", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "10g"}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/6", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}}, Column: 7, ID: 7, Row: 1, FailureDomain: 1, Display: pointer.To(6), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/7", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "10g"}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/7", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}}, Column: 8, ID: 8, Row: 1, FailureDomain: 1, Display: pointer.To(7), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/8", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "10g"}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/8", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}}, Column: 9, ID: 9, Row: 1, FailureDomain: 1, Display: pointer.To(8), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/9", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "10g"}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/9", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}}, Column: 10, ID: 10, Row: 1, FailureDomain: 1, Display: pointer.To(9), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/1/0", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "10g"}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/1/0", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}}, Column: 11, ID: 11, Row: 1, FailureDomain: 1, Display: pointer.To(10), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/1/1", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "10g"}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/1/1", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}}, Column: 12, ID: 12, Row: 1, FailureDomain: 1, Display: pointer.To(11), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/1/2", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "10g"}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/1/2", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}}, Column: 13, ID: 13, Row: 1, FailureDomain: 1, Display: pointer.To(12), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/1/3", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "10g"}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/1/3", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}}, Column: 14, ID: 14, Row: 1, FailureDomain: 1, Display: pointer.To(13), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/1/4", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "10g"}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/1/4", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}}, Column: 15, ID: 15, Row: 1, FailureDomain: 1, Display: pointer.To(14), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/1/5", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "10g"}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/1/5", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}}, Column: 16, ID: 16, Row: 1, FailureDomain: 1, Display: pointer.To(15), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/1/6", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "10g"}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/1/6", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}}, Column: 17, ID: 17, Row: 1, FailureDomain: 1, Display: pointer.To(16), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/1/7", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "10g"}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/1/7", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}}, Column: 18, ID: 18, Row: 1, FailureDomain: 1, Display: pointer.To(17), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/1/8", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "10g"}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/1/8", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}}, Column: 19, ID: 19, Row: 1, FailureDomain: 1, Display: pointer.To(18), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/1/9", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "10g"}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/1/9", State: enum.InterfaceStateActive, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}}, Column: 20, ID: 20, Row: 1, FailureDomain: 1, Display: pointer.To(19), Slot: 0},
				},
			},
			update: device.Profile{
				Label:                       "_test_ Juniper_EX4400-48F",
				Selector:                    device.Selector{OsVersion: ".*", Model: "EX4400-48F", Os: "Junos", Manufacturer: "Juniper"},
				DeviceProfileType:           enum.DeviceProfileType{Value: "monolithic"},
				SoftwareCapabilities:        device.SoftwareCapabilities{Onie: false, ConfigApplySupport: "complete_only", LxcSupport: false},
				ReferenceDesignCapabilities: &device.ReferenceDesignCapabilities{Datacenter: enum.RefDesignCapabilityFullSupport, Freeform: enum.RefDesignCapabilityFullSupport},
				ChassisProfileID:            "",
				HardwareCapabilities: device.HardwareCapabilities{
					FormFactor:      "1RU",
					BFDSupported:    false,
					ECMPLimit:       64,
					RAM:             4,
					Userland:        64,
					ASIC:            "T3",
					RoutingInstance: device.FeatureVersions{device.FeatureVersion{Version: ".*", Enabled: true}},
					VxlanSupported:  false,
					CPU:             "x86",
				},
				SlotCount: pointer.To(0),
				Ports: []device.Port{
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/0", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/0", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 0, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 1, ID: 1, Row: 1, FailureDomain: 1, Display: pointer.To(0), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/1", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/1", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 1, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 1, ID: 2, Row: 2, FailureDomain: 1, Display: pointer.To(1), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/2", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/2", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 2, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 2, ID: 3, Row: 1, FailureDomain: 1, Display: pointer.To(2), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/3", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/3", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 3, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 2, ID: 4, Row: 2, FailureDomain: 1, Display: pointer.To(3), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/4", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/4", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 4, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 3, ID: 5, Row: 1, FailureDomain: 1, Display: pointer.To(4), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/5", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/5", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 5, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 3, ID: 6, Row: 2, FailureDomain: 1, Display: pointer.To(5), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/6", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/6", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 6, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 4, ID: 7, Row: 1, FailureDomain: 1, Display: pointer.To(6), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/7", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/7", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 7, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 4, ID: 8, Row: 2, FailureDomain: 1, Display: pointer.To(7), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/8", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/8", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 8, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 5, ID: 9, Row: 1, FailureDomain: 1, Display: pointer.To(8), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/9", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/9", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 9, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 5, ID: 10, Row: 2, FailureDomain: 1, Display: pointer.To(9), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/10", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/10", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 10, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 6, ID: 11, Row: 1, FailureDomain: 1, Display: pointer.To(10), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/11", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/11", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 11, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 6, ID: 12, Row: 2, FailureDomain: 1, Display: pointer.To(11), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/12", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/12", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 12, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 7, ID: 13, Row: 1, FailureDomain: 1, Display: pointer.To(12), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/13", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/13", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 13, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 7, ID: 14, Row: 2, FailureDomain: 1, Display: pointer.To(13), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/14", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/14", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 14, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 8, ID: 15, Row: 1, FailureDomain: 1, Display: pointer.To(14), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/15", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/15", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 15, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 8, ID: 16, Row: 2, FailureDomain: 1, Display: pointer.To(15), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/16", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/16", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 16, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 9, ID: 17, Row: 1, FailureDomain: 1, Display: pointer.To(16), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/17", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/17", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 17, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 9, ID: 18, Row: 2, FailureDomain: 1, Display: pointer.To(17), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/18", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/18", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 18, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 10, ID: 19, Row: 1, FailureDomain: 1, Display: pointer.To(18), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/19", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/19", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 19, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 10, ID: 20, Row: 2, FailureDomain: 1, Display: pointer.To(19), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/20", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/20", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 20, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 11, ID: 21, Row: 1, FailureDomain: 1, Display: pointer.To(20), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/21", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/21", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 21, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 11, ID: 22, Row: 2, FailureDomain: 1, Display: pointer.To(21), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/22", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/22", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 22, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 12, ID: 23, Row: 1, FailureDomain: 1, Display: pointer.To(22), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/23", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/23", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 23, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 12, ID: 24, Row: 2, FailureDomain: 1, Display: pointer.To(23), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/24", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/24", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 24, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 13, ID: 25, Row: 1, FailureDomain: 1, Display: pointer.To(24), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/25", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/25", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 25, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 13, ID: 26, Row: 2, FailureDomain: 1, Display: pointer.To(25), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/26", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/26", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 26, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 14, ID: 27, Row: 1, FailureDomain: 1, Display: pointer.To(26), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/27", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/27", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 27, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 14, ID: 28, Row: 2, FailureDomain: 1, Display: pointer.To(27), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/28", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/28", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 28, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 15, ID: 29, Row: 1, FailureDomain: 1, Display: pointer.To(28), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/29", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/29", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 29, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 15, ID: 30, Row: 2, FailureDomain: 1, Display: pointer.To(29), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/30", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/30", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 30, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 16, ID: 31, Row: 1, FailureDomain: 1, Display: pointer.To(30), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/31", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/31", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 31, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 16, ID: 32, Row: 2, FailureDomain: 1, Display: pointer.To(31), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/32", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/32", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 32, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 17, ID: 33, Row: 1, FailureDomain: 1, Display: pointer.To(32), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/33", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/33", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 33, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 17, ID: 34, Row: 2, FailureDomain: 1, Display: pointer.To(33), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/34", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/34", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 34, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 18, ID: 35, Row: 1, FailureDomain: 1, Display: pointer.To(34), Slot: 0},
					{ConnectorType: "sfp", Panel: 1, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/35", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "1G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/35", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": false, "fpc": 0, "pic": 0, "port": 35, "speed": "100m"}, "interface": {"speed": ""}}`), Speed: "100M"}}}}, Column: 18, ID: 36, Row: 2, FailureDomain: 1, Display: pointer.To(35), Slot: 0},
					{ConnectorType: "sfp+", Panel: 2, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "xe-0/0/36", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/36", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "1g"}}`), Speed: "1G"}}}, {ID: 3, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/36", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"auto_negotiation": false, "link_mode": "full-duplex", "speed": "1g"}}`), Speed: "1G"}}}}, Column: 1, ID: 37, Row: 1, FailureDomain: 1, Display: pointer.To(36), Slot: 0},
					{ConnectorType: "sfp+", Panel: 2, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "xe-0/0/37", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/37", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "1g"}}`), Speed: "1G"}}}, {ID: 3, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/37", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"auto_negotiation": false, "link_mode": "full-duplex", "speed": "1g"}}`), Speed: "1G"}}}}, Column: 1, ID: 38, Row: 2, FailureDomain: 1, Display: pointer.To(37), Slot: 0},
					{ConnectorType: "sfp+", Panel: 2, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "xe-0/0/38", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/38", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "1g"}}`), Speed: "1G"}}}, {ID: 3, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/38", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"auto_negotiation": false, "link_mode": "full-duplex", "speed": "1g"}}`), Speed: "1G"}}}}, Column: 2, ID: 39, Row: 1, FailureDomain: 1, Display: pointer.To(38), Slot: 0},
					{ConnectorType: "sfp+", Panel: 2, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "xe-0/0/39", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/39", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "1g"}}`), Speed: "1G"}}}, {ID: 3, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/39", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"auto_negotiation": false, "link_mode": "full-duplex", "speed": "1g"}}`), Speed: "1G"}}}}, Column: 2, ID: 40, Row: 2, FailureDomain: 1, Display: pointer.To(39), Slot: 0},
					{ConnectorType: "sfp+", Panel: 2, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "xe-0/0/40", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/40", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "1g"}}`), Speed: "1G"}}}, {ID: 3, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/40", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"auto_negotiation": false, "link_mode": "full-duplex", "speed": "1g"}}`), Speed: "1G"}}}}, Column: 3, ID: 41, Row: 1, FailureDomain: 1, Display: pointer.To(40), Slot: 0},
					{ConnectorType: "sfp+", Panel: 2, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "xe-0/0/41", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/41", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "1g"}}`), Speed: "1G"}}}, {ID: 3, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/41", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"auto_negotiation": false, "link_mode": "full-duplex", "speed": "1g"}}`), Speed: "1G"}}}}, Column: 3, ID: 42, Row: 2, FailureDomain: 1, Display: pointer.To(41), Slot: 0},
					{ConnectorType: "sfp+", Panel: 2, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "xe-0/0/42", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/42", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "1g"}}`), Speed: "1G"}}}, {ID: 3, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/42", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"auto_negotiation": false, "link_mode": "full-duplex", "speed": "1g"}}`), Speed: "1G"}}}}, Column: 4, ID: 43, Row: 1, FailureDomain: 1, Display: pointer.To(42), Slot: 0},
					{ConnectorType: "sfp+", Panel: 2, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "xe-0/0/43", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/43", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "1g"}}`), Speed: "1G"}}}, {ID: 3, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/43", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"auto_negotiation": false, "link_mode": "full-duplex", "speed": "1g"}}`), Speed: "1G"}}}}, Column: 4, ID: 44, Row: 2, FailureDomain: 1, Display: pointer.To(43), Slot: 0},
					{ConnectorType: "sfp+", Panel: 2, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "xe-0/0/44", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/44", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "1g"}}`), Speed: "1G"}}}, {ID: 3, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/44", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"auto_negotiation": false, "link_mode": "full-duplex", "speed": "1g"}}`), Speed: "1G"}}}}, Column: 5, ID: 45, Row: 1, FailureDomain: 1, Display: pointer.To(44), Slot: 0},
					{ConnectorType: "sfp+", Panel: 2, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "xe-0/0/45", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/45", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "1g"}}`), Speed: "1G"}}}, {ID: 3, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/45", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"auto_negotiation": false, "link_mode": "full-duplex", "speed": "1g"}}`), Speed: "1G"}}}}, Column: 5, ID: 46, Row: 2, FailureDomain: 1, Display: pointer.To(45), Slot: 0},
					{ConnectorType: "sfp+", Panel: 2, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "xe-0/0/46", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/46", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "1g"}}`), Speed: "1G"}}}, {ID: 3, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/46", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"auto_negotiation": false, "link_mode": "full-duplex", "speed": "1g"}}`), Speed: "1G"}}}}, Column: 6, ID: 47, Row: 1, FailureDomain: 1, Display: pointer.To(46), Slot: 0},
					{ConnectorType: "sfp+", Panel: 2, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "xe-0/0/47", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/47", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "1g"}}`), Speed: "1G"}}}, {ID: 3, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/0/47", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"auto_negotiation": false, "link_mode": "full-duplex", "speed": "1g"}}`), Speed: "1G"}}}}, Column: 6, ID: 48, Row: 2, FailureDomain: 1, Display: pointer.To(47), Slot: 0},
					{ConnectorType: "qsfp28", Panel: 3, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "et-0/1/0", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "100G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "et-0/1/0:0", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": true, "fpc": 0, "pic": 1, "port": 0, "speed": "25g"}, "interface": {"speed": ""}}`), Speed: "25G"}, {ID: 2, Name: "et-0/1/0:1", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": true, "fpc": 0, "pic": 1, "port": 0, "speed": "25g"}, "interface": {"speed": ""}}`), Speed: "25G"}, {ID: 3, Name: "et-0/1/0:2", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": true, "fpc": 0, "pic": 1, "port": 0, "speed": "25g"}, "interface": {"speed": ""}}`), Speed: "25G"}, {ID: 4, Name: "et-0/1/0:3", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": true, "fpc": 0, "pic": 1, "port": 0, "speed": "25g"}, "interface": {"speed": ""}}`), Speed: "25G"}}}, {ID: 3, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "xe-0/1/0:0", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": true, "fpc": 0, "pic": 1, "port": 0, "speed": "10g"}, "interface": {"speed": ""}}`), Speed: "10G"}, {ID: 2, Name: "xe-0/1/0:1", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": true, "fpc": 0, "pic": 1, "port": 0, "speed": "10g"}, "interface": {"speed": ""}}`), Speed: "10G"}, {ID: 3, Name: "xe-0/1/0:2", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": true, "fpc": 0, "pic": 1, "port": 0, "speed": "10g"}, "interface": {"speed": ""}}`), Speed: "10G"}, {ID: 4, Name: "xe-0/1/0:3", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": true, "fpc": 0, "pic": 1, "port": 0, "speed": "10g"}, "interface": {"speed": ""}}`), Speed: "10G"}}}}, Column: 1, ID: 49, Row: 1, FailureDomain: 1, Display: pointer.To(48), Slot: 0},
					{ConnectorType: "qsfp28", Panel: 3, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "et-0/1/1", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "100G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "et-0/1/1:0", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": true, "fpc": 0, "pic": 1, "port": 1, "speed": "25g"}, "interface": {"speed": ""}}`), Speed: "25G"}, {ID: 2, Name: "et-0/1/1:1", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": true, "fpc": 0, "pic": 1, "port": 1, "speed": "25g"}, "interface": {"speed": ""}}`), Speed: "25G"}, {ID: 3, Name: "et-0/1/1:2", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": true, "fpc": 0, "pic": 1, "port": 1, "speed": "25g"}, "interface": {"speed": ""}}`), Speed: "25G"}, {ID: 4, Name: "et-0/1/1:3", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": true, "fpc": 0, "pic": 1, "port": 1, "speed": "25g"}, "interface": {"speed": ""}}`), Speed: "25G"}}}, {ID: 3, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "xe-0/1/1:0", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": true, "fpc": 0, "pic": 1, "port": 1, "speed": "10g"}, "interface": {"speed": ""}}`), Speed: "10G"}, {ID: 2, Name: "xe-0/1/1:1", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": true, "fpc": 0, "pic": 1, "port": 1, "speed": "10g"}, "interface": {"speed": ""}}`), Speed: "10G"}, {ID: 3, Name: "xe-0/1/1:2", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": true, "fpc": 0, "pic": 1, "port": 1, "speed": "10g"}, "interface": {"speed": ""}}`), Speed: "10G"}, {ID: 4, Name: "xe-0/1/1:3", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"breakout": true, "fpc": 0, "pic": 1, "port": 1, "speed": "10g"}, "interface": {"speed": ""}}`), Speed: "10G"}}}}, Column: 1, ID: 50, Row: 2, FailureDomain: 1, Display: pointer.To(49), Slot: 0},
					{ConnectorType: "sfp+", Panel: 4, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "xe-0/2/0", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/2/0", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "1g"}}`), Speed: "1G"}}}, {ID: 3, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/2/0", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"auto_negotiation": false, "link_mode": "full-duplex", "speed": "1g"}}`), Speed: "1G"}}}}, Column: 1, ID: 51, Row: 1, FailureDomain: 1, Display: pointer.To(50), Slot: 0},
					{ConnectorType: "sfp+", Panel: 4, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "xe-0/2/1", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/2/1", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "1g"}}`), Speed: "1G"}}}, {ID: 3, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/2/1", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"auto_negotiation": false, "link_mode": "full-duplex", "speed": "1g"}}`), Speed: "1G"}}}}, Column: 2, ID: 52, Row: 1, FailureDomain: 1, Display: pointer.To(51), Slot: 0},
					{ConnectorType: "sfp+", Panel: 4, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "xe-0/2/2", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/2/2", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "1g"}}`), Speed: "1G"}}}, {ID: 3, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/2/2", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"auto_negotiation": false, "link_mode": "full-duplex", "speed": "1g"}}`), Speed: "1G"}}}}, Column: 3, ID: 53, Row: 1, FailureDomain: 1, Display: pointer.To(52), Slot: 0},
					{ConnectorType: "sfp+", Panel: 4, Transformations: []device.Transformation{{ID: 1, IsDefault: true, Interfaces: []device.TransformationInterface{{ID: 1, Name: "xe-0/2/3", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": ""}}`), Speed: "10G"}}}, {ID: 2, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/2/3", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"speed": "1g"}}`), Speed: "1G"}}}, {ID: 3, IsDefault: false, Interfaces: []device.TransformationInterface{{ID: 1, Name: "ge-0/2/3", State: enum.InterfaceState{Value: "active"}, Setting: pointer.To(`{"global": {"speed": ""}, "interface": {"auto_negotiation": false, "link_mode": "full-duplex", "speed": "1g"}}`), Speed: "1G"}}}}, Column: 4, ID: 54, Row: 1, FailureDomain: 1, Display: pointer.To(53), Slot: 0},
				},
				PhysicalDevice: true,
			},
		},
	}

	for tName, tCase := range testCases {
		t.Run(tName, func(t *testing.T) {
			for _, client := range clients {
				create, update := tCase.create, tCase.update // because we modify the test objects based on API version below
				t.Run(client.Name(), func(t *testing.T) {
					t.Parallel()
					ctx := testutils.ContextWithTestID(ctx, t)

					// remove features not supported by earlier API versions
					if !compatibility.DeviceProfileHasRefdesignCapabilities.Check(version.Must(version.NewVersion(client.Client.ApiVersion()))) {
						create.ReferenceDesignCapabilities = nil
						update.ReferenceDesignCapabilities = nil
					}

					var id string
					var err error
					var obj device.Profile

					t.Log("create object")
					id, err = client.Client.CreateDeviceProfile(ctx, create)
					require.NoError(t, err)

					t.Log("ensure the object is deleted even if tests fail")
					testutils.CleanupWithFreshContext(t, 2*time.Minute, func(ctx context.Context) error {
						_ = client.Client.DeleteDeviceProfile(ctx, id)
						return nil
					})

					t.Log("retrieve the object by ID and validate")
					obj, err = client.Client.GetDeviceProfile(ctx, id)
					require.NoError(t, err)
					idPtr := obj.ID()
					require.NotNil(t, idPtr)
					require.Equal(t, id, *idPtr)
					comparedevice.DeviceProfile(t, create, obj)

					t.Log("retrieve the object by label and validate")
					gdpblCtx, cf := context.WithTimeout(ctx, 2*time.Minute)
					obj, err = client.Client.GetDeviceProfileByLabel(gdpblCtx, create.Label)
					cf()
					require.NoError(t, err)
					idPtr = obj.ID()
					require.NotNil(t, idPtr)
					require.Equal(t, id, *idPtr)
					comparedevice.DeviceProfile(t, create, obj)

					t.Log("retrieve the list of IDs (ours must be in there)")
					ids, err := client.Client.ListDeviceProfiles(ctx)
					require.NoError(t, err)
					require.Contains(t, ids, id)

					t.Log("retrieve the list of objects (ours must be in there) and validate")
					gdpCtx, cf := context.WithTimeout(ctx, 2*time.Minute)
					objs, err := client.Client.GetDeviceProfiles(gdpCtx)
					cf()
					require.NoError(t, err)
					objPtr := slice.MustFindByID(objs, id)
					require.NotNil(t, objPtr)
					obj = *objPtr
					idPtr = obj.ID()
					require.NotNil(t, idPtr)
					require.Equal(t, id, *idPtr)
					comparedevice.DeviceProfile(t, create, obj)

					t.Log("update the object and validate")
					update.SetID(id)
					require.NotNil(t, update.ID())
					require.Equal(t, id, *update.ID())
					err = client.Client.UpdateDeviceProfile(ctx, update)
					require.NoError(t, err)

					t.Log("retrieve the updated object by ID and validate")
					obj, err = client.Client.GetDeviceProfile(ctx, id)
					require.NoError(t, err)
					idPtr = obj.ID()
					require.NotNil(t, idPtr)
					require.Equal(t, id, *idPtr)
					comparedevice.DeviceProfile(t, update, obj)

					t.Log("restore the object to the original state")
					create.SetID(id)
					require.NotNil(t, create.ID())
					require.Equal(t, id, *update.ID())
					err = client.Client.UpdateDeviceProfile(ctx, create)
					require.NoError(t, err)

					t.Log("retrieve the object by ID and validate")
					obj, err = client.Client.GetDeviceProfile(ctx, id)
					require.NoError(t, err)
					idPtr = obj.ID()
					require.NotNil(t, idPtr)
					require.Equal(t, id, *idPtr)
					comparedevice.DeviceProfile(t, create, obj)

					t.Log("delete the object")
					err = client.Client.DeleteDeviceProfile(ctx, id)
					require.NoError(t, err)

					t.Log("below this point we're expecting to fail to find, update or delete the object")
					var ace apstra.ClientErr

					t.Log("get the object by ID")
					_, err = client.Client.GetDeviceProfile(ctx, id)
					require.Error(t, err)
					require.ErrorAs(t, err, &ace)
					require.Equal(t, apstra.ErrNotfound, ace.Type())

					t.Log("get the object by label")
					gdpblCtx, cf = context.WithTimeout(ctx, 2*time.Minute)
					_, err = client.Client.GetDeviceProfileByLabel(gdpblCtx, create.Label)
					cf()
					require.Error(t, err)
					require.ErrorAs(t, err, &ace)
					require.Equal(t, apstra.ErrNotfound, ace.Type())

					t.Log("retrieve the list of IDs (ours must *not* be in there)")
					ids, err = client.Client.ListDeviceProfiles(ctx)
					require.NoError(t, err)
					require.NotContains(t, ids, id)

					t.Log("retrieve the list of objects (ours must *not* be in there)")
					gdpCtx, cf = context.WithTimeout(ctx, 2*time.Minute)
					objs, err = client.Client.GetDeviceProfiles(gdpCtx)
					cf()
					require.NoError(t, err)
					objPtr = slice.MustFindByID(objs, id)
					require.Nil(t, objPtr)

					t.Log("update the object")
					err = client.Client.UpdateDeviceProfile(ctx, update)
					require.Error(t, err)
					require.ErrorAs(t, err, &ace)
					require.Equal(t, apstra.ErrNotfound, ace.Type())

					t.Log("delete the object")
					err = client.Client.DeleteDeviceProfile(ctx, id)
					require.Error(t, err)
					require.ErrorAs(t, err, &ace)
					require.Equal(t, apstra.ErrNotfound, ace.Type())
				})
			}
		})
	}
}
