# Copyright (c) Juniper Networks, Inc., 2023-2025.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Go package

on: [push]

jobs:
  go-tools:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: '1.24.6'

      - name: go generate
        run: |
          go generate ./...
          make check-repo-clean

      - name: go fmt
        run: make fmt-check

      - name: gofumpt
        run: |
          git fetch origin main --depth 1
          make fumpt-check

      - name: go vet
        run: make vet

      - name: compliance
        run: make compliance-check

      - name: build-tags
        run: make check-build-tags
