name: Go package

on: [push]

jobs:
  go-tools:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: '1.22.5'

      - name: go fmt
        run: make fmt-check

      - name: gofumpt
        run: |
          git fetch origin main --depth 1
          make fumpt-check

      - name: go vet
        run: make vet

      - name: compliance
        run: make compliance-check
