#  Copyright (c) Juniper Networks, Inc., 2024-2024.
#  All rights reserved.
#  SPDX-License-Identifier: Apache-2.0

name: Go package

on: [push]

jobs:
  license-header-check:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: license check
        run: |
          git fetch origin main --depth 1
          make fumpt-check
