#  Copyright (c) Juniper Networks, Inc., 2024-2024.
#  All rights reserved.
#  SPDX-License-Identifier: Apache-2.0

name: Go package

on: [push]

jobs:
  license-header-check:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: fetch main
        run: |
          git fetch origin main

      - name: unshallow
        run: |
          git pull --unshallow

      - name: license header check
        run: |
          make license-header-check
